import type { Metadata } from 'next'
import { Toast } from '@heroui/react'
import { ThemeProvider as NextThemesProvider } from 'next-themes'
import BackTop from '@/components/BackTop'
import FullLoading from '@/components/FullLoading'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh-CN" suppressHydrationWarning>
      <head>
        <link rel="stylesheet" href="https://cdn.baiwumm.com/fonts/MapleMono-CN-Regular/result.css" />
      </head>
      <body className="bg-background text-foreground">
        <NextThemesProvider attribute="class">
          <FullLoading>
            {children}
          </FullLoading>
          <BackTop />
          <Toast.Provider placement="top" />
        </NextThemesProvider>
      </body>
    </html>
  )
}
